name: Python CI

on: [push, pull_request]

jobs:
  test-and-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout репозиторію
        uses: actions/checkout@v3

      - name: Встановити Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Встановити залежності
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install flake8

      - name: Запустити тести
        run: pytest --maxfail=1 --disable-warnings

      - name: Перевірка стилю коду (PEP8)
        run: flake8 . --max-line-length=120
